version: '3.8'
networks:
  funny_movies:
    driver: bridge

services:
  web:
    build: .
    environment:
      RAILS_ENV: development
      RAILS_DB_HOST: db
      RAILS_DB_USER_NAME: postgres
      RAILS_DB_PASSWORD: p@ssw0rd
      REDIS_URL: 'redis://redis:6379/1'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - sidekiq
    networks:
      - funny_movies

  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redisdata-redis:/data
    networks:
      - funny_movies

  sidekiq:
    build: .
    environment:
      REDIS_URL: 'redis://redis:6379/1'
    command: bash -c "bundle exec sidekiq -q default -q fetch_video_info"
    depends_on:
      - db
      - redis
    networks:
      - funny_movies

volumes:
  pgdata-db:
  redisdata-redis:
