version: '3.8'
networks:
  funny_movies:
    driver: bridge

services:
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '4000:4000'
    depends_on:
      - redis
      - sidekiq
    networks:
      - funny_movies

  redis:
    image: redis:latest
    restart: always
    command: redis-server --port 6379
    ports:
      - '6378:6379'
    volumes:
      - redisdata-redis:/data
    networks:
      - funny_movies

  sidekiq:
    build: .
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    command: bash -c "bundle exec sidekiq -q default -q fetch_video_info"
    depends_on:
      - redis
    networks:
      - funny_movies

volumes:
  pgdata-db:
  redisdata-redis:
